#!/usr/bin/env bash
# script to report information about server domains
# shellcheck disable=SC2086

check_domain() {
        # awk will use record separator as space
        # space separated list of subdomains
        SUBDOMAINS='www lb-01 web-01 web-02'

        if [ -z "$1" ]; then
                exit
        fi

        domain="$1"
        subdomain="$2"

        # no subdomain specified, do all
        if [ -z "$subdomain" ]; then
                echo "$SUBDOMAINS" | awk -v domain="$domain" 'BEGIN { RS=" " }
          {
            split($0,ARR," ");
            cmd = "dig " ARR[1] "." domain " | grep -A1 \"ANSWER SECTION:\" | tail -n1";
            system(cmd);
            close(cmd)
          }' |
                awk '{
            split($0, DOMS, ".");
            print "The subdomain " DOMS[1] " is a " $4 " record and points to " $5
          }'
        else
                dig "$subdomain.$domain" |
                grep -A1 "ANSWER SECTION:" |
                tail -n1 |
                awk '{
            split($0, DOMS, ".");
            print "The subdomain " DOMS[1] " is a " $4 " record and points to " $5
          }'
        fi
}
