#!/usr/bin/env bash
# to aduit the DNS records for given subdomains

print_domain_subdomain () {
	dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r
	local domain="$1"
	local subdomain="$2"

	if [ -z "$subdomain" ]; then
		subdomains=("www" "lb-1" "web-01" "web-02")
	else
		subdomains=("$subdomain")
	fi

	for sub in "$subdomains[@]}"; do
