#!/usr/bin/env bash
# Installs nginx web server

#!/usr/bin/env bash
# Commands to install Nginx on Web-Sever-01

# Updating Packages before making Installations
sudo apt-get update
sudo apt-get -y install nginx

# Configuring the Uncomplicated Firewall (UFW) to allow incoming traffic for the Nginx HTTP service
sudo ufw allow 'Nginx HTTP'

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Testing Nginx configurations for Syntax errors
sudo nginx -t

# Restarting Nginx
sudo service nginx start

#apt-get update
#apt-get install -y nginx
#echo "Hello World!" > /var/www/html/index.html
#cat <<EOL > /etc/nginx/sites-available/default
#server {
 #   listen 80 default_server;
  #  listen [::]:80 default_server;
   # root /var/www/html;
    #index index.html;
    #location / {
     #   try_files $uri $uri/ /index.html;
    #}
#}
#EOL
#service nginx start
