#!/usr/bin/env bash
# Installs nginx web server

apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    location / {
        return 200 'Hello World!';
    }
}" > /etc/nginx/sites-available/default
service nginx start
