#!/usr/bin/env bash
# Open the 80 port
rm /etc/nginx/sites-enabled/default
# link with the correct config
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
