#!/usr/bin/env bash
#configure nginx server to listen for port 80 instead  of 8080
#this is spam
#this is spam
sed -i 's/listen 8080;/listen 80;/g' /etc/nginx/sites-enabled/default
service nginx restart
