#!/usr/bin/env bash
#Display a list of currently running processes
#a: Show processes for all users.
#u: Display more detailed information, including the user-oriented format.
#x: Include processes that do not have a controlling terminal (TTY).
#f: Show a tree-like structure to represent the process hierarchy.

ps -auxf 
