#!/usr/bin/env bash
#Dispalys bad luck in 4th iteration
#Displays good luck in 88th iteration
#Displays Best School in other iterations

i=0

while [ $i -lt 10 ]
do
	if [ $i = 3 ]
	then
		echo "bad luck"
	elif [ $i = 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	let i+=1
done
