# Use an official Apache image as a base image
FROM httpd:2.4

# Copy your custom configuration file if needed
# COPY ./my-httpd.conf /usr/local/apache2/conf/httpd.conf

# Optionally, copy your website files to the container
# COPY ./my-website /usr/local/apache2/htdocs/
